# Application Name
spring.application.name=sample

# Active Profile (dev or prod)
# Default to 'dev' if not specified via environment variable
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

# Profile-specific configurations are in application-dev.properties and application-prod.properties

# Razorpay Configuration
razorpay.key.id=rzp_test_SSm2ZSKmU3cLGo
razorpay.key.secret=Av46Nb5ag1Gi6GvlOAH0qt7y